# This includes the config necessary for a washer and dryer.
# Code for dishwasher and mini-washer may be commented out as-needed,
# and are presented only for reference purposes.

# NOTE: YOUR ENTITY NAMES MAY BE DIFFERENT, THEN THIS WON'T WORK WITHOUT TWEAKING
# =================================================================================
# If your washer doesn't have entities named sensor.washer, sensor.washer_run_state
# (and similar for dryer), you have to change the names throughout here!

# NOTE: THIS CODE EXPECTS YOUR THINQ INTEGRATION TO RETURN ENGLISH STRINGS
# =================================================================================
# if your LG account is in another region/language, this will probably break unless
# you take the time to change out state strings like "Standby". Do this by watching
# your machine's entities change states during a run, or look at its history.

template:
  - sensor:
      - unique_id: washer_door_lock
        default_entity_id: sensor.washer_door_lock
        name: "Washer Door Lock"
        state: "{{ state_attr('sensor.washer','door_lock') }}"

      #      - unique_id: mini_washer_door_lock
      #        default_entity_id: sensor.mini_washer_door_lock
      #        name: "Mini Washer Door Lock"
      #        state: "{{ state_attr('sensor.mini_washer','door_lock') }}"

      #      - unique_id: dishwasher_door_open
      #        default_entity_id: sensor.dishwasher_door_open
      #        name: "Dish Washer Door Lock"
      #        state: "{{ state_attr('sensor.dishwasher','door_open') }}"

      - unique_id: washer_time_display
        default_entity_id: sensor.washer_time_display
        name: "Washer Time Display"
        state: >
          {% if is_state('sensor.washer_run_state', '-') %}
          {% elif is_state('sensor.washer_run_state', 'unavailable') %}
          {% elif is_state('sensor.washer_run_state', 'Standby') %}
            -:--
          {% else %}
            {{ state_attr("sensor.washer","remain_time").split(":")[:-1] | join(':') }}
          {% endif %}

      #     - unique_id: mini_washer_time_display
      #       default_entity_id: sensor.mini_washer_time_display
      #       name: "Mini Washer Time Display"
      #       state: >
      #         {% if is_state('sensor.mini_washer_run_state', '-') %}
      #         {% elif is_state('sensor.mini_washer_run_state', 'unavailable') %}
      #         {% elif is_state('sensor.mini_washer_run_state', 'Standby') %}
      #           -:--
      #         {% else %}
      #           {{ state_attr("sensor.mini_washer","remain_time").split(":")[:-1] | join(':') }}
      #         {% endif %}

      - unique_id: dryer_time_display
        default_entity_id: sensor.dryer_time_display
        name: "Dryer Time Display"
        state: >
          {% if is_state('sensor.dryer_run_state', '-') %}
          {% elif is_state('sensor.dryer_run_state', 'unavailable') %}
          {% elif is_state('sensor.dryer_run_state', 'Standby') %}
            -:--
          {% else %}
            {{ state_attr("sensor.dryer","remain_time").split(":")[:-1] | join(':') }}
          {% endif %}

      #      - unique_id: dishwasher_time_display
      #        default_entity_id: sensor.dishwasher_time_display
      #        name: "Dish Washer Time Display"
      #        state: >
      #          {% if is_state('sensor.dishwasher_run_state', '-') %}
      #          {% elif is_state('sensor.dishwasher_run_state', 'unavailable') %}
      #          {% elif is_state('sensor.dishwasher_run_state', 'Standby') %}
      #            -:--
      #          {% else %}
      #            {{ state_attr("sensor.dishwasher","remain_time").split(":")[:-1] | join(':') }}
      #          {% endif %}

      - unique_id: blank
        default_entity_id: sensor.blank
        name: "Blank Sensor"
        state: ""
